# Generated by Django 4.1.7 on 2023-03-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'در مورد توانا', 'verbose_name_plural': 'در موارد'},
        ),
    ]
