# Generated by Django 4.1.7 on 2023-03-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_helpers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpers',
            options={'verbose_name': 'کمک کننده', 'verbose_name_plural': 'کمک کننده ها'},
        ),
        migrations.AlterField(
            model_name='helpers',
            name='count',
            field=models.CharField(max_length=50, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='helpers',
            name='image',
            field=models.ImageField(upload_to='helpers_pictures', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='helpers',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام'),
        ),
    ]
