# Generated by Django 4.1.7 on 2023-03-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_details_donations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details_donations',
            options={'verbose_name': 'جزئیات کمک', 'verbose_name_plural': 'جزئیات کمک ها'},
        ),
    ]
