# Generated by Django 4.1.7 on 2023-04-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title_Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'عنوان بخش بودجه',
                'verbose_name_plural': 'عناوین بودجه',
            },
        ),
    ]
