# Generated by Django 4.1.7 on 2023-04-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_title_expenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('count', models.CharField(max_length=100, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'بودجه',
                'verbose_name_plural': 'بودجه',
            },
        ),
    ]
