# Generated by Django 4.1.7 on 2023-04-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=100, verbose_name='شماره های تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('whatsapp', models.CharField(max_length=100, verbose_name='واتساپ')),
                ('facebook', models.CharField(max_length=100, verbose_name='فسبوک')),
            ],
            options={
                'verbose_name': 'شبکه های اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
